//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.14-hudson-jaxb-ri-2.1-60--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 01:00:44 PM MST 
//


package dsp.dell_services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ActivityDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActivityDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Buid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="DispatchNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SolutionSteps" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Owner" type="{dsp:dell.services.dispatch}TechnicianDataType" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StatusDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubStatusDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="StatusDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="RecordType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceAttributes" type="{dsp:dell.services.dispatch}ArrayOfServiceAttributesType" minOccurs="0"/>
 *         &lt;element name="ReasonCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RepeatCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="RepeatReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReverseAgency" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CustomerDeferDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DeferTimeZone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Approver" type="{dsp:dell.services.dispatch}TechnicianDataType" minOccurs="0"/>
 *         &lt;element name="ReasonCodeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LaborStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LaborStatusDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="PartsStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PartsStatusDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="SubType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ActivityType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerHeat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ActivityNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSUsed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="APSUsed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DispatchType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="Federal"/>
 *               &lt;enumeration value="Oconus"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ServiceSchedule" type="{dsp:dell.services.dispatch}ServiceScheduleDataType" minOccurs="0"/>
 *         &lt;element name="SubRegion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DispatchCreationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="PurchaseOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Waybills" type="{dsp:dell.services.dispatch}ArrayOfWaybillDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActivityDataType", propOrder = {
    "id",
    "buid",
    "dispatchNumber",
    "description",
    "solutionSteps",
    "priority",
    "groupName",
    "owner",
    "status",
    "statusDescription",
    "subStatus",
    "subStatusDate",
    "statusDate",
    "recordType",
    "serviceAttributes",
    "reasonCode",
    "repeatCount",
    "repeatReason",
    "reverseAgency",
    "customerDeferDate",
    "deferTimeZone",
    "approver",
    "reasonCodeDescription",
    "laborStatusCode",
    "laborStatusDate",
    "partsStatusCode",
    "partsStatusDate",
    "subType",
    "activityType",
    "customerHeat",
    "activityNote",
    "avsUsed",
    "apsUsed",
    "dispatchType",
    "serviceSchedule",
    "subRegion",
    "dispatchCreationDate",
    "purchaseOrderNumber",
    "waybills"
})
public class ActivityDataType {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Buid")
    protected long buid;
    @XmlElement(name = "DispatchNumber")
    protected long dispatchNumber;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "SolutionSteps")
    protected String solutionSteps;
    @XmlElement(name = "Priority")
    protected String priority;
    @XmlElement(name = "GroupName")
    protected String groupName;
    @XmlElement(name = "Owner")
    protected TechnicianDataType owner;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "StatusDescription")
    protected String statusDescription;
    @XmlElement(name = "SubStatus")
    protected String subStatus;
    @XmlElement(name = "SubStatusDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar subStatusDate;
    @XmlElement(name = "StatusDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar statusDate;
    @XmlElement(name = "RecordType")
    protected String recordType;
    @XmlElement(name = "ServiceAttributes")
    protected ArrayOfServiceAttributesType serviceAttributes;
    @XmlElement(name = "ReasonCode", required = true)
    protected String reasonCode;
    @XmlElement(name = "RepeatCount")
    protected Long repeatCount;
    @XmlElement(name = "RepeatReason")
    protected String repeatReason;
    @XmlElement(name = "ReverseAgency")
    protected boolean reverseAgency;
    @XmlElement(name = "CustomerDeferDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar customerDeferDate;
    @XmlElement(name = "DeferTimeZone")
    protected String deferTimeZone;
    @XmlElement(name = "Approver")
    protected TechnicianDataType approver;
    @XmlElement(name = "ReasonCodeDescription")
    protected String reasonCodeDescription;
    @XmlElement(name = "LaborStatusCode")
    protected String laborStatusCode;
    @XmlElement(name = "LaborStatusDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar laborStatusDate;
    @XmlElement(name = "PartsStatusCode")
    protected String partsStatusCode;
    @XmlElement(name = "PartsStatusDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar partsStatusDate;
    @XmlElement(name = "SubType")
    protected String subType;
    @XmlElement(name = "ActivityType")
    protected String activityType;
    @XmlElement(name = "CustomerHeat")
    protected String customerHeat;
    @XmlElement(name = "ActivityNote")
    protected String activityNote;
    @XmlElement(name = "AVSUsed")
    protected Boolean avsUsed;
    @XmlElement(name = "APSUsed")
    protected Boolean apsUsed;
    @XmlElement(name = "DispatchType")
    protected String dispatchType;
    @XmlElement(name = "ServiceSchedule")
    protected ServiceScheduleDataType serviceSchedule;
    @XmlElement(name = "SubRegion")
    protected String subRegion;
    @XmlElement(name = "DispatchCreationDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dispatchCreationDate;
    @XmlElement(name = "PurchaseOrderNumber")
    protected String purchaseOrderNumber;
    @XmlElement(name = "Waybills")
    protected ArrayOfWaybillDataType waybills;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the buid property.
     * 
     */
    public long getBuid() {
        return buid;
    }

    /**
     * Sets the value of the buid property.
     * 
     */
    public void setBuid(long value) {
        this.buid = value;
    }

    /**
     * Gets the value of the dispatchNumber property.
     * 
     */
    public long getDispatchNumber() {
        return dispatchNumber;
    }

    /**
     * Sets the value of the dispatchNumber property.
     * 
     */
    public void setDispatchNumber(long value) {
        this.dispatchNumber = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the solutionSteps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolutionSteps() {
        return solutionSteps;
    }

    /**
     * Sets the value of the solutionSteps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolutionSteps(String value) {
        this.solutionSteps = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicianDataType }
     *     
     */
    public TechnicianDataType getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicianDataType }
     *     
     */
    public void setOwner(TechnicianDataType value) {
        this.owner = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusDescription() {
        return statusDescription;
    }

    /**
     * Sets the value of the statusDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusDescription(String value) {
        this.statusDescription = value;
    }

    /**
     * Gets the value of the subStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubStatus() {
        return subStatus;
    }

    /**
     * Sets the value of the subStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubStatus(String value) {
        this.subStatus = value;
    }

    /**
     * Gets the value of the subStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubStatusDate() {
        return subStatusDate;
    }

    /**
     * Sets the value of the subStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubStatusDate(XMLGregorianCalendar value) {
        this.subStatusDate = value;
    }

    /**
     * Gets the value of the statusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStatusDate(XMLGregorianCalendar value) {
        this.statusDate = value;
    }

    /**
     * Gets the value of the recordType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordType(String value) {
        this.recordType = value;
    }

    /**
     * Gets the value of the serviceAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfServiceAttributesType }
     *     
     */
    public ArrayOfServiceAttributesType getServiceAttributes() {
        return serviceAttributes;
    }

    /**
     * Sets the value of the serviceAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfServiceAttributesType }
     *     
     */
    public void setServiceAttributes(ArrayOfServiceAttributesType value) {
        this.serviceAttributes = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the repeatCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRepeatCount() {
        return repeatCount;
    }

    /**
     * Sets the value of the repeatCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRepeatCount(Long value) {
        this.repeatCount = value;
    }

    /**
     * Gets the value of the repeatReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepeatReason() {
        return repeatReason;
    }

    /**
     * Sets the value of the repeatReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepeatReason(String value) {
        this.repeatReason = value;
    }

    /**
     * Gets the value of the reverseAgency property.
     * 
     */
    public boolean isReverseAgency() {
        return reverseAgency;
    }

    /**
     * Sets the value of the reverseAgency property.
     * 
     */
    public void setReverseAgency(boolean value) {
        this.reverseAgency = value;
    }

    /**
     * Gets the value of the customerDeferDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCustomerDeferDate() {
        return customerDeferDate;
    }

    /**
     * Sets the value of the customerDeferDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCustomerDeferDate(XMLGregorianCalendar value) {
        this.customerDeferDate = value;
    }

    /**
     * Gets the value of the deferTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeferTimeZone() {
        return deferTimeZone;
    }

    /**
     * Sets the value of the deferTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeferTimeZone(String value) {
        this.deferTimeZone = value;
    }

    /**
     * Gets the value of the approver property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicianDataType }
     *     
     */
    public TechnicianDataType getApprover() {
        return approver;
    }

    /**
     * Sets the value of the approver property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicianDataType }
     *     
     */
    public void setApprover(TechnicianDataType value) {
        this.approver = value;
    }

    /**
     * Gets the value of the reasonCodeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCodeDescription() {
        return reasonCodeDescription;
    }

    /**
     * Sets the value of the reasonCodeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCodeDescription(String value) {
        this.reasonCodeDescription = value;
    }

    /**
     * Gets the value of the laborStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaborStatusCode() {
        return laborStatusCode;
    }

    /**
     * Sets the value of the laborStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaborStatusCode(String value) {
        this.laborStatusCode = value;
    }

    /**
     * Gets the value of the laborStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLaborStatusDate() {
        return laborStatusDate;
    }

    /**
     * Sets the value of the laborStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLaborStatusDate(XMLGregorianCalendar value) {
        this.laborStatusDate = value;
    }

    /**
     * Gets the value of the partsStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartsStatusCode() {
        return partsStatusCode;
    }

    /**
     * Sets the value of the partsStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartsStatusCode(String value) {
        this.partsStatusCode = value;
    }

    /**
     * Gets the value of the partsStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPartsStatusDate() {
        return partsStatusDate;
    }

    /**
     * Sets the value of the partsStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPartsStatusDate(XMLGregorianCalendar value) {
        this.partsStatusDate = value;
    }

    /**
     * Gets the value of the subType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubType() {
        return subType;
    }

    /**
     * Sets the value of the subType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubType(String value) {
        this.subType = value;
    }

    /**
     * Gets the value of the activityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityType() {
        return activityType;
    }

    /**
     * Sets the value of the activityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityType(String value) {
        this.activityType = value;
    }

    /**
     * Gets the value of the customerHeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerHeat() {
        return customerHeat;
    }

    /**
     * Sets the value of the customerHeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerHeat(String value) {
        this.customerHeat = value;
    }

    /**
     * Gets the value of the activityNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityNote() {
        return activityNote;
    }

    /**
     * Sets the value of the activityNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityNote(String value) {
        this.activityNote = value;
    }

    /**
     * Gets the value of the avsUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAVSUsed() {
        return avsUsed;
    }

    /**
     * Sets the value of the avsUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAVSUsed(Boolean value) {
        this.avsUsed = value;
    }

    /**
     * Gets the value of the apsUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAPSUsed() {
        return apsUsed;
    }

    /**
     * Sets the value of the apsUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAPSUsed(Boolean value) {
        this.apsUsed = value;
    }

    /**
     * Gets the value of the dispatchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispatchType() {
        return dispatchType;
    }

    /**
     * Sets the value of the dispatchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispatchType(String value) {
        this.dispatchType = value;
    }

    /**
     * Gets the value of the serviceSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceScheduleDataType }
     *     
     */
    public ServiceScheduleDataType getServiceSchedule() {
        return serviceSchedule;
    }

    /**
     * Sets the value of the serviceSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceScheduleDataType }
     *     
     */
    public void setServiceSchedule(ServiceScheduleDataType value) {
        this.serviceSchedule = value;
    }

    /**
     * Gets the value of the subRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubRegion() {
        return subRegion;
    }

    /**
     * Sets the value of the subRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubRegion(String value) {
        this.subRegion = value;
    }

    /**
     * Gets the value of the dispatchCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDispatchCreationDate() {
        return dispatchCreationDate;
    }

    /**
     * Sets the value of the dispatchCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDispatchCreationDate(XMLGregorianCalendar value) {
        this.dispatchCreationDate = value;
    }

    /**
     * Gets the value of the purchaseOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseOrderNumber() {
        return purchaseOrderNumber;
    }

    /**
     * Sets the value of the purchaseOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseOrderNumber(String value) {
        this.purchaseOrderNumber = value;
    }

    /**
     * Gets the value of the waybills property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfWaybillDataType }
     *     
     */
    public ArrayOfWaybillDataType getWaybills() {
        return waybills;
    }

    /**
     * Sets the value of the waybills property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfWaybillDataType }
     *     
     */
    public void setWaybills(ArrayOfWaybillDataType value) {
        this.waybills = value;
    }

}
