//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.14-hudson-jaxb-ri-2.1-60--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 01:00:44 PM MST 
//


package dsp.dell_services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DispatchMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispatchMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageHeader" type="{dsp:dell.services.dispatch}HeaderOperationType"/>
 *         &lt;element name="VendorTransaction" type="{dsp:dell.services.dispatch}VendorTransactionDataType"/>
 *         &lt;element name="ServiceRequest" type="{dsp:dell.services.dispatch}ServiceRequestType"/>
 *         &lt;element name="Activity" type="{dsp:dell.services.dispatch}ActivityDataType"/>
 *         &lt;element name="Account" type="{dsp:dell.services.dispatch}AccountDataType"/>
 *         &lt;element name="Asset" type="{dsp:dell.services.dispatch}AssetDataType" minOccurs="0"/>
 *         &lt;element name="Order" type="{dsp:dell.services.dispatch}OrderIdType" minOccurs="0"/>
 *         &lt;element name="Technician" type="{dsp:dell.services.dispatch}TechnicianDataType" minOccurs="0"/>
 *         &lt;element name="Customer" type="{dsp:dell.services.dispatch}CustomerDataType"/>
 *         &lt;element name="Address" type="{dsp:dell.services.dispatch}AddressDataType"/>
 *         &lt;element name="SecondaryAddress" type="{dsp:dell.services.dispatch}AddressDataType" minOccurs="0"/>
 *         &lt;element name="Contact" type="{dsp:dell.services.dispatch}ContactDataType"/>
 *         &lt;element name="AlternateContact" type="{dsp:dell.services.dispatch}ContactDataType" minOccurs="0"/>
 *         &lt;element name="Comments" type="{dsp:dell.services.dispatch}ArrayOfCommentsType" minOccurs="0"/>
 *         &lt;element name="PartsOrdered" type="{dsp:dell.services.dispatch}ArrayOfPartsType" minOccurs="0"/>
 *         &lt;element name="LogisticsDepots" type="{dsp:dell.services.dispatch}ArrayOfLocationType" minOccurs="0"/>
 *         &lt;element name="ExchangeOrder" type="{dsp:dell.services.dispatch}OrderDataType" minOccurs="0"/>
 *         &lt;element name="LogisticsDetails" type="{dsp:dell.services.dispatch}ArrayOfLogisticDetailDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispatchMessageType", propOrder = {
    "messageHeader",
    "vendorTransaction",
    "serviceRequest",
    "activity",
    "account",
    "asset",
    "orderInfo",
    "technician",
    "customer",
    "address",
    "secondaryAddress",
    "contact",
    "alternateContact",
    "comments",
    "partsOrdered",
    "logisticsDepots",
    "exchangeOrder",
    "logisticsDetails"
})
@XmlRootElement(name = "DispatchDataMessage")
public class DispatchDataMessage {

    @XmlElement(name = "MessageHeader", required = true)
    protected HeaderOperationType messageHeader;
    @XmlElement(name = "VendorTransaction", required = true)
    protected VendorTransactionDataType vendorTransaction;
    @XmlElement(name = "ServiceRequest", required = true)
    protected ServiceRequestType serviceRequest;
    @XmlElement(name = "Activity", required = true)
    protected ActivityDataType activity;
    @XmlElement(name = "Account", required = true)
    protected AccountDataType account;
    @XmlElement(name = "Asset")
    protected AssetDataType asset;
    @XmlElement(name = "Order")
    protected OrderIdType orderInfo;
    @XmlElement(name = "Technician")
    protected TechnicianDataType technician;
    @XmlElement(name = "Customer", required = true)
    protected CustomerDataType customer;
    @XmlElement(name = "Address", required = true)
    protected AddressDataType address;
    @XmlElement(name = "SecondaryAddress")
    protected AddressDataType secondaryAddress;
    @XmlElement(name = "Contact", required = true)
    protected ContactDataType contact;
    @XmlElement(name = "AlternateContact")
    protected ContactDataType alternateContact;
    @XmlElement(name = "Comments")
    protected ArrayOfCommentsType comments;
    @XmlElement(name = "PartsOrdered")
    protected ArrayOfPartsType partsOrdered;
    @XmlElement(name = "LogisticsDepots")
    protected ArrayOfLocationType logisticsDepots;
    @XmlElement(name = "ExchangeOrder")
    protected OrderDataType exchangeOrder;
    @XmlElement(name = "LogisticsDetails")
    protected ArrayOfLogisticDetailDataType logisticsDetails;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderOperationType }
     *     
     */
    public HeaderOperationType getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderOperationType }
     *     
     */
    public void setMessageHeader(HeaderOperationType value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the vendorTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link VendorTransactionDataType }
     *     
     */
    public VendorTransactionDataType getVendorTransaction() {
        return vendorTransaction;
    }

    /**
     * Sets the value of the vendorTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorTransactionDataType }
     *     
     */
    public void setVendorTransaction(VendorTransactionDataType value) {
        this.vendorTransaction = value;
    }

    /**
     * Gets the value of the serviceRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceRequestType }
     *     
     */
    public ServiceRequestType getServiceRequest() {
        return serviceRequest;
    }

    /**
     * Sets the value of the serviceRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceRequestType }
     *     
     */
    public void setServiceRequest(ServiceRequestType value) {
        this.serviceRequest = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityDataType }
     *     
     */
    public ActivityDataType getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityDataType }
     *     
     */
    public void setActivity(ActivityDataType value) {
        this.activity = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link AccountDataType }
     *     
     */
    public AccountDataType getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountDataType }
     *     
     */
    public void setAccount(AccountDataType value) {
        this.account = value;
    }

    /**
     * Gets the value of the asset property.
     * 
     * @return
     *     possible object is
     *     {@link AssetDataType }
     *     
     */
    public AssetDataType getAsset() {
        return asset;
    }

    /**
     * Sets the value of the asset property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetDataType }
     *     
     */
    public void setAsset(AssetDataType value) {
        this.asset = value;
    }

    /**
     * Gets the value of the orderInfo property.
     * 
     * @return
     *     possible object is
     *     {@link OrderIdType }
     *     
     */
    public OrderIdType getOrderInfo() {
        return orderInfo;
    }

    /**
     * Sets the value of the orderInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderIdType }
     *     
     */
    public void setOrderInfo(OrderIdType value) {
        this.orderInfo = value;
    }

    /**
     * Gets the value of the technician property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicianDataType }
     *     
     */
    public TechnicianDataType getTechnician() {
        return technician;
    }

    /**
     * Sets the value of the technician property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicianDataType }
     *     
     */
    public void setTechnician(TechnicianDataType value) {
        this.technician = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDataType }
     *     
     */
    public CustomerDataType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDataType }
     *     
     */
    public void setCustomer(CustomerDataType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDataType }
     *     
     */
    public AddressDataType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDataType }
     *     
     */
    public void setAddress(AddressDataType value) {
        this.address = value;
    }

    /**
     * Gets the value of the secondaryAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDataType }
     *     
     */
    public AddressDataType getSecondaryAddress() {
        return secondaryAddress;
    }

    /**
     * Sets the value of the secondaryAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDataType }
     *     
     */
    public void setSecondaryAddress(AddressDataType value) {
        this.secondaryAddress = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDataType }
     *     
     */
    public ContactDataType getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDataType }
     *     
     */
    public void setContact(ContactDataType value) {
        this.contact = value;
    }

    /**
     * Gets the value of the alternateContact property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDataType }
     *     
     */
    public ContactDataType getAlternateContact() {
        return alternateContact;
    }

    /**
     * Sets the value of the alternateContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDataType }
     *     
     */
    public void setAlternateContact(ContactDataType value) {
        this.alternateContact = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCommentsType }
     *     
     */
    public ArrayOfCommentsType getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCommentsType }
     *     
     */
    public void setComments(ArrayOfCommentsType value) {
        this.comments = value;
    }

    /**
     * Gets the value of the partsOrdered property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfPartsType }
     *     
     */
    public ArrayOfPartsType getPartsOrdered() {
        return partsOrdered;
    }

    /**
     * Sets the value of the partsOrdered property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfPartsType }
     *     
     */
    public void setPartsOrdered(ArrayOfPartsType value) {
        this.partsOrdered = value;
    }

    /**
     * Gets the value of the logisticsDepots property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfLocationType }
     *     
     */
    public ArrayOfLocationType getLogisticsDepots() {
        return logisticsDepots;
    }

    /**
     * Sets the value of the logisticsDepots property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfLocationType }
     *     
     */
    public void setLogisticsDepots(ArrayOfLocationType value) {
        this.logisticsDepots = value;
    }

    /**
     * Gets the value of the exchangeOrder property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDataType }
     *     
     */
    public OrderDataType getExchangeOrder() {
        return exchangeOrder;
    }

    /**
     * Sets the value of the exchangeOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDataType }
     *     
     */
    public void setExchangeOrder(OrderDataType value) {
        this.exchangeOrder = value;
    }

    /**
     * Gets the value of the logisticsDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfLogisticDetailDataType }
     *     
     */
    public ArrayOfLogisticDetailDataType getLogisticsDetails() {
        return logisticsDetails;
    }

    /**
     * Sets the value of the logisticsDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfLogisticDetailDataType }
     *     
     */
    public void setLogisticsDetails(ArrayOfLogisticDetailDataType value) {
        this.logisticsDetails = value;
    }

}
