//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.14-hudson-jaxb-ri-2.1-60--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 01:00:44 PM MST 
//


package dsp.dell_services;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dsp.dell_services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrderShippingDataTypeShippingDate_QNAME = new QName("dsp:dell.services.dispatch", "ShippingDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dsp.dell_services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DispatchDataMessage }
     * 
     */
    public DispatchDataMessage createDispatchDataMessage() {
        return new DispatchDataMessage();
    }

    /**
     * Create an instance of {@link HeaderOperationType }
     * 
     */
    public HeaderOperationType createHeaderOperationType() {
        return new HeaderOperationType();
    }

    /**
     * Create an instance of {@link VendorTransactionDataType }
     * 
     */
    public VendorTransactionDataType createVendorTransactionDataType() {
        return new VendorTransactionDataType();
    }

    /**
     * Create an instance of {@link ServiceRequestType }
     * 
     */
    public ServiceRequestType createServiceRequestType() {
        return new ServiceRequestType();
    }

    /**
     * Create an instance of {@link ActivityDataType }
     * 
     */
    public ActivityDataType createActivityDataType() {
        return new ActivityDataType();
    }

    /**
     * Create an instance of {@link AccountDataType }
     * 
     */
    public AccountDataType createAccountDataType() {
        return new AccountDataType();
    }

    /**
     * Create an instance of {@link AssetDataType }
     * 
     */
    public AssetDataType createAssetDataType() {
        return new AssetDataType();
    }

    /**
     * Create an instance of {@link OrderIdType }
     * 
     */
    public OrderIdType createOrderIdType() {
        return new OrderIdType();
    }

    /**
     * Create an instance of {@link TechnicianDataType }
     * 
     */
    public TechnicianDataType createTechnicianDataType() {
        return new TechnicianDataType();
    }

    /**
     * Create an instance of {@link CustomerDataType }
     * 
     */
    public CustomerDataType createCustomerDataType() {
        return new CustomerDataType();
    }

    /**
     * Create an instance of {@link AddressDataType }
     * 
     */
    public AddressDataType createAddressDataType() {
        return new AddressDataType();
    }

    /**
     * Create an instance of {@link ContactDataType }
     * 
     */
    public ContactDataType createContactDataType() {
        return new ContactDataType();
    }

    /**
     * Create an instance of {@link ArrayOfCommentsType }
     * 
     */
    public ArrayOfCommentsType createArrayOfCommentsType() {
        return new ArrayOfCommentsType();
    }

    /**
     * Create an instance of {@link ArrayOfPartsType }
     * 
     */
    public ArrayOfPartsType createArrayOfPartsType() {
        return new ArrayOfPartsType();
    }

    /**
     * Create an instance of {@link ArrayOfLocationType }
     * 
     */
    public ArrayOfLocationType createArrayOfLocationType() {
        return new ArrayOfLocationType();
    }

    /**
     * Create an instance of {@link OrderDataType }
     * 
     */
    public OrderDataType createOrderDataType() {
        return new OrderDataType();
    }

    /**
     * Create an instance of {@link ArrayOfLogisticDetailDataType }
     * 
     */
    public ArrayOfLogisticDetailDataType createArrayOfLogisticDetailDataType() {
        return new ArrayOfLogisticDetailDataType();
    }

    /**
     * Create an instance of {@link ExceptionType }
     * 
     */
    public ExceptionType createExceptionType() {
        return new ExceptionType();
    }

    /**
     * Create an instance of {@link PartStatusDataType }
     * 
     */
    public PartStatusDataType createPartStatusDataType() {
        return new PartStatusDataType();
    }

    /**
     * Create an instance of {@link ArrayOfStatusDateType }
     * 
     */
    public ArrayOfStatusDateType createArrayOfStatusDateType() {
        return new ArrayOfStatusDateType();
    }

    /**
     * Create an instance of {@link StatusDateType }
     * 
     */
    public StatusDateType createStatusDateType() {
        return new StatusDateType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link ServiceScheduleDataType }
     * 
     */
    public ServiceScheduleDataType createServiceScheduleDataType() {
        return new ServiceScheduleDataType();
    }

    /**
     * Create an instance of {@link PartDataType }
     * 
     */
    public PartDataType createPartDataType() {
        return new PartDataType();
    }

    /**
     * Create an instance of {@link WaybillDataType }
     * 
     */
    public WaybillDataType createWaybillDataType() {
        return new WaybillDataType();
    }

    /**
     * Create an instance of {@link PhoneDataType }
     * 
     */
    public PhoneDataType createPhoneDataType() {
        return new PhoneDataType();
    }

    /**
     * Create an instance of {@link TransportStatusDataType }
     * 
     */
    public TransportStatusDataType createTransportStatusDataType() {
        return new TransportStatusDataType();
    }

    /**
     * Create an instance of {@link CommentDataType }
     * 
     */
    public CommentDataType createCommentDataType() {
        return new CommentDataType();
    }

    /**
     * Create an instance of {@link OrderShippingDataType }
     * 
     */
    public OrderShippingDataType createOrderShippingDataType() {
        return new OrderShippingDataType();
    }

    /**
     * Create an instance of {@link ArrayOfServiceAttributesType }
     * 
     */
    public ArrayOfServiceAttributesType createArrayOfServiceAttributesType() {
        return new ArrayOfServiceAttributesType();
    }

    /**
     * Create an instance of {@link ArrayOfExceptionType }
     * 
     */
    public ArrayOfExceptionType createArrayOfExceptionType() {
        return new ArrayOfExceptionType();
    }

    /**
     * Create an instance of {@link ServiceAttributeType }
     * 
     */
    public ServiceAttributeType createServiceAttributeType() {
        return new ServiceAttributeType();
    }

    /**
     * Create an instance of {@link ArrayOfOrderShippingDataType }
     * 
     */
    public ArrayOfOrderShippingDataType createArrayOfOrderShippingDataType() {
        return new ArrayOfOrderShippingDataType();
    }

    /**
     * Create an instance of {@link ArrayOfWaybillDataType }
     * 
     */
    public ArrayOfWaybillDataType createArrayOfWaybillDataType() {
        return new ArrayOfWaybillDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "dsp:dell.services.dispatch", name = "ShippingDate", scope = OrderShippingDataType.class)
    public JAXBElement<XMLGregorianCalendar> createOrderShippingDataTypeShippingDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OrderShippingDataTypeShippingDate_QNAME, XMLGregorianCalendar.class, OrderShippingDataType.class, value);
    }

}
