//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.14-hudson-jaxb-ri-2.1-60--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 01:00:44 PM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "dsp:dell.services.dispatch", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dsp.dell_services;
