//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.14-hudson-jaxb-ri-2.1-60--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 01:00:44 PM MST 
//


package dsp.dell_services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PartStatusDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartStatusDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SequenceNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="LineNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="SubLineNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ProviderId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Part" type="{dsp:dell.services.dispatch}PartDataType"/>
 *         &lt;element name="PODSignatory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Location" type="{dsp:dell.services.dispatch}LocationType" minOccurs="0"/>
 *         &lt;element name="PartStatusDates" type="{dsp:dell.services.dispatch}ArrayOfStatusDateType" minOccurs="0"/>
 *         &lt;element name="ShippingData" type="{dsp:dell.services.dispatch}OrderShippingDataType" minOccurs="0"/>
 *         &lt;element name="HubName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipQty" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="FileCreatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DlpRefNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WaybillNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReportedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="GroundCarrierName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StatusDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartStatusDataType", propOrder = {
    "sequenceNumber",
    "lineNumber",
    "subLineNumber",
    "providerId",
    "part",
    "podSignatory",
    "statusCode",
    "location",
    "partStatusDates",
    "shippingData",
    "hubName",
    "shipQty",
    "fileCreatedDate",
    "dlpRefNumber",
    "waybillNumber",
    "reportedDate",
    "groundCarrierName",
    "statusDate"
})
public class PartStatusDataType {

    @XmlElement(name = "SequenceNumber")
    protected long sequenceNumber;
    @XmlElement(name = "LineNumber")
    protected long lineNumber;
    @XmlElement(name = "SubLineNumber")
    protected long subLineNumber;
    @XmlElement(name = "ProviderId")
    protected String providerId;
    @XmlElement(name = "Part", required = true)
    protected PartDataType part;
    @XmlElement(name = "PODSignatory")
    protected String podSignatory;
    @XmlElement(name = "StatusCode")
    protected String statusCode;
    @XmlElement(name = "Location")
    protected LocationType location;
    @XmlElement(name = "PartStatusDates")
    protected ArrayOfStatusDateType partStatusDates;
    @XmlElement(name = "ShippingData")
    protected OrderShippingDataType shippingData;
    @XmlElement(name = "HubName")
    protected String hubName;
    @XmlElement(name = "ShipQty")
    protected Long shipQty;
    @XmlElement(name = "FileCreatedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fileCreatedDate;
    @XmlElement(name = "DlpRefNumber")
    protected String dlpRefNumber;
    @XmlElement(name = "WaybillNumber")
    protected String waybillNumber;
    @XmlElement(name = "ReportedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reportedDate;
    @XmlElement(name = "GroundCarrierName")
    protected String groundCarrierName;
    @XmlElement(name = "StatusDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar statusDate;

    /**
     * Gets the value of the sequenceNumber property.
     * 
     */
    public long getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     */
    public void setSequenceNumber(long value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the lineNumber property.
     * 
     */
    public long getLineNumber() {
        return lineNumber;
    }

    /**
     * Sets the value of the lineNumber property.
     * 
     */
    public void setLineNumber(long value) {
        this.lineNumber = value;
    }

    /**
     * Gets the value of the subLineNumber property.
     * 
     */
    public long getSubLineNumber() {
        return subLineNumber;
    }

    /**
     * Sets the value of the subLineNumber property.
     * 
     */
    public void setSubLineNumber(long value) {
        this.subLineNumber = value;
    }

    /**
     * Gets the value of the providerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderId() {
        return providerId;
    }

    /**
     * Sets the value of the providerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderId(String value) {
        this.providerId = value;
    }

    /**
     * Gets the value of the part property.
     * 
     * @return
     *     possible object is
     *     {@link PartDataType }
     *     
     */
    public PartDataType getPart() {
        return part;
    }

    /**
     * Sets the value of the part property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartDataType }
     *     
     */
    public void setPart(PartDataType value) {
        this.part = value;
    }

    /**
     * Gets the value of the podSignatory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPODSignatory() {
        return podSignatory;
    }

    /**
     * Sets the value of the podSignatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPODSignatory(String value) {
        this.podSignatory = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setLocation(LocationType value) {
        this.location = value;
    }

    /**
     * Gets the value of the partStatusDates property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfStatusDateType }
     *     
     */
    public ArrayOfStatusDateType getPartStatusDates() {
        return partStatusDates;
    }

    /**
     * Sets the value of the partStatusDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfStatusDateType }
     *     
     */
    public void setPartStatusDates(ArrayOfStatusDateType value) {
        this.partStatusDates = value;
    }

    /**
     * Gets the value of the shippingData property.
     * 
     * @return
     *     possible object is
     *     {@link OrderShippingDataType }
     *     
     */
    public OrderShippingDataType getShippingData() {
        return shippingData;
    }

    /**
     * Sets the value of the shippingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderShippingDataType }
     *     
     */
    public void setShippingData(OrderShippingDataType value) {
        this.shippingData = value;
    }

    /**
     * Gets the value of the hubName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHubName() {
        return hubName;
    }

    /**
     * Sets the value of the hubName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHubName(String value) {
        this.hubName = value;
    }

    /**
     * Gets the value of the shipQty property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getShipQty() {
        return shipQty;
    }

    /**
     * Sets the value of the shipQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setShipQty(Long value) {
        this.shipQty = value;
    }

    /**
     * Gets the value of the fileCreatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFileCreatedDate() {
        return fileCreatedDate;
    }

    /**
     * Sets the value of the fileCreatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFileCreatedDate(XMLGregorianCalendar value) {
        this.fileCreatedDate = value;
    }

    /**
     * Gets the value of the dlpRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlpRefNumber() {
        return dlpRefNumber;
    }

    /**
     * Sets the value of the dlpRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlpRefNumber(String value) {
        this.dlpRefNumber = value;
    }

    /**
     * Gets the value of the waybillNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaybillNumber() {
        return waybillNumber;
    }

    /**
     * Sets the value of the waybillNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaybillNumber(String value) {
        this.waybillNumber = value;
    }

    /**
     * Gets the value of the reportedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportedDate() {
        return reportedDate;
    }

    /**
     * Sets the value of the reportedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportedDate(XMLGregorianCalendar value) {
        this.reportedDate = value;
    }

    /**
     * Gets the value of the groundCarrierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroundCarrierName() {
        return groundCarrierName;
    }

    /**
     * Sets the value of the groundCarrierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroundCarrierName(String value) {
        this.groundCarrierName = value;
    }

    /**
     * Gets the value of the statusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStatusDate(XMLGregorianCalendar value) {
        this.statusDate = value;
    }

}
