//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.14-hudson-jaxb-ri-2.1-60--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 01:00:44 PM MST 
//


package dsp.dell_services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for VendorTransactionDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VendorTransactionDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VendorId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EventCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VendorReplyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VendorReplyDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VendorTechId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EventDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="VendorDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExceptionList" type="{dsp:dell.services.dispatch}ArrayOfExceptionType" minOccurs="0"/>
 *         &lt;element name="FileCreatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="AckLoadedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StatusTimeFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StatusDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="GroundCarrierName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MSGType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RejectionReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VendorTransactionDataType", propOrder = {
    "vendorId",
    "eventCode",
    "vendorReplyCode",
    "vendorReplyDescription",
    "referenceNumber",
    "vendorTechId",
    "eventDate",
    "vendorDate",
    "comments",
    "exceptionList",
    "fileCreatedDate",
    "ackLoadedDate",
    "statusCode",
    "statusTimeFlag",
    "statusDate",
    "groundCarrierName",
    "msgType",
    "rejectionReason"
})
public class VendorTransactionDataType {

    @XmlElement(name = "VendorId", required = true)
    protected String vendorId;
    @XmlElement(name = "EventCode", required = true)
    protected String eventCode;
    @XmlElement(name = "VendorReplyCode")
    protected String vendorReplyCode;
    @XmlElement(name = "VendorReplyDescription")
    protected String vendorReplyDescription;
    @XmlElement(name = "ReferenceNumber")
    protected String referenceNumber;
    @XmlElement(name = "VendorTechId")
    protected String vendorTechId;
    @XmlElement(name = "EventDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventDate;
    @XmlElement(name = "VendorDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vendorDate;
    @XmlElement(name = "Comments")
    protected String comments;
    @XmlElement(name = "ExceptionList")
    protected ArrayOfExceptionType exceptionList;
    @XmlElement(name = "FileCreatedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fileCreatedDate;
    @XmlElement(name = "AckLoadedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ackLoadedDate;
    @XmlElement(name = "StatusCode")
    protected String statusCode;
    @XmlElement(name = "StatusTimeFlag")
    protected String statusTimeFlag;
    @XmlElement(name = "StatusDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar statusDate;
    @XmlElement(name = "GroundCarrierName")
    protected String groundCarrierName;
    @XmlElement(name = "MSGType")
    protected String msgType;
    @XmlElement(name = "RejectionReason")
    protected String rejectionReason;

    /**
     * Gets the value of the vendorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorId() {
        return vendorId;
    }

    /**
     * Sets the value of the vendorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorId(String value) {
        this.vendorId = value;
    }

    /**
     * Gets the value of the eventCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventCode() {
        return eventCode;
    }

    /**
     * Sets the value of the eventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventCode(String value) {
        this.eventCode = value;
    }

    /**
     * Gets the value of the vendorReplyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorReplyCode() {
        return vendorReplyCode;
    }

    /**
     * Sets the value of the vendorReplyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorReplyCode(String value) {
        this.vendorReplyCode = value;
    }

    /**
     * Gets the value of the vendorReplyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorReplyDescription() {
        return vendorReplyDescription;
    }

    /**
     * Sets the value of the vendorReplyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorReplyDescription(String value) {
        this.vendorReplyDescription = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNumber(String value) {
        this.referenceNumber = value;
    }

    /**
     * Gets the value of the vendorTechId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorTechId() {
        return vendorTechId;
    }

    /**
     * Sets the value of the vendorTechId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorTechId(String value) {
        this.vendorTechId = value;
    }

    /**
     * Gets the value of the eventDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventDate() {
        return eventDate;
    }

    /**
     * Sets the value of the eventDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventDate(XMLGregorianCalendar value) {
        this.eventDate = value;
    }

    /**
     * Gets the value of the vendorDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVendorDate() {
        return vendorDate;
    }

    /**
     * Sets the value of the vendorDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVendorDate(XMLGregorianCalendar value) {
        this.vendorDate = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the exceptionList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfExceptionType }
     *     
     */
    public ArrayOfExceptionType getExceptionList() {
        return exceptionList;
    }

    /**
     * Sets the value of the exceptionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfExceptionType }
     *     
     */
    public void setExceptionList(ArrayOfExceptionType value) {
        this.exceptionList = value;
    }

    /**
     * Gets the value of the fileCreatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFileCreatedDate() {
        return fileCreatedDate;
    }

    /**
     * Sets the value of the fileCreatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFileCreatedDate(XMLGregorianCalendar value) {
        this.fileCreatedDate = value;
    }

    /**
     * Gets the value of the ackLoadedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAckLoadedDate() {
        return ackLoadedDate;
    }

    /**
     * Sets the value of the ackLoadedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAckLoadedDate(XMLGregorianCalendar value) {
        this.ackLoadedDate = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusTimeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusTimeFlag() {
        return statusTimeFlag;
    }

    /**
     * Sets the value of the statusTimeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusTimeFlag(String value) {
        this.statusTimeFlag = value;
    }

    /**
     * Gets the value of the statusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStatusDate(XMLGregorianCalendar value) {
        this.statusDate = value;
    }

    /**
     * Gets the value of the groundCarrierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroundCarrierName() {
        return groundCarrierName;
    }

    /**
     * Sets the value of the groundCarrierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroundCarrierName(String value) {
        this.groundCarrierName = value;
    }

    /**
     * Gets the value of the msgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSGType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSGType(String value) {
        this.msgType = value;
    }

    /**
     * Gets the value of the rejectionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectionReason() {
        return rejectionReason;
    }

    /**
     * Sets the value of the rejectionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectionReason(String value) {
        this.rejectionReason = value;
    }

}
