Insert into SHOPPING.LOYALTY_STATUS_CODES (LOYALTY_STATUS,STATUS) values (0,'Green
');
Insert into SHOPPING.LOYALTY_STATUS_CODES (LOYALTY_STATUS,STATUS) values (2,'Gold');
Insert into SHOPPING.LOYALTY_STATUS_CODES (LOYALTY_STATUS,STATUS) values (1,'Silver');
Insert into SHOPPING.LOYALTY_STATUS_CODES (LOYALTY_STATUS,STATUS) values (3,'Platinum');
COMMIT;
