//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.14-hudson-jaxb-ri-2.1-60--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.31 at 11:02:50 AM MST 
//


package poc.dell;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DispatchAlertType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispatchAlertType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alertType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="alertTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dispatchID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceTAG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="corticonResponse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="currentDispatchId" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="currentStatusCode" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="currentServiceClass" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="previousDispatchId" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="previousStatusCode" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="previousServiceClass" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispatchAlertType", propOrder = {
    "alertType",
    "alertTime",
    "dispatchID",
    "statusCode",
    "serviceHours",
    "serviceLevel",
    "serviceTAG",
    "corticonResponse",
    "currentDispatchId",
    "currentStatusCode",
    "currentServiceClass",
    "previousDispatchId",
    "previousStatusCode",
    "previousServiceClass"
})
@XmlRootElement(name = "DispatchAlert")
public class DispatchAlert {

    protected String alertType;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar alertTime;
    protected String dispatchID;
    protected String statusCode;
    protected String serviceHours;
    protected String serviceLevel;
    protected String serviceTAG;
    protected String corticonResponse;
    protected Object currentDispatchId;
    protected Object currentStatusCode;
    protected Object currentServiceClass;
    protected Object previousDispatchId;
    protected Object previousStatusCode;
    protected Object previousServiceClass;

    /**
     * Gets the value of the alertType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertType() {
        return alertType;
    }

    /**
     * Sets the value of the alertType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertType(String value) {
        this.alertType = value;
    }

    /**
     * Gets the value of the alertTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAlertTime() {
        return alertTime;
    }

    /**
     * Sets the value of the alertTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAlertTime(XMLGregorianCalendar value) {
        this.alertTime = value;
    }

    /**
     * Gets the value of the dispatchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispatchID() {
        return dispatchID;
    }

    /**
     * Sets the value of the dispatchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispatchID(String value) {
        this.dispatchID = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the serviceHours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceHours() {
        return serviceHours;
    }

    /**
     * Sets the value of the serviceHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceHours(String value) {
        this.serviceHours = value;
    }

    /**
     * Gets the value of the serviceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceLevel() {
        return serviceLevel;
    }

    /**
     * Sets the value of the serviceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceLevel(String value) {
        this.serviceLevel = value;
    }

    /**
     * Gets the value of the serviceTAG property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceTAG() {
        return serviceTAG;
    }

    /**
     * Sets the value of the serviceTAG property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceTAG(String value) {
        this.serviceTAG = value;
    }

    /**
     * Gets the value of the corticonResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorticonResponse() {
        return corticonResponse;
    }

    /**
     * Sets the value of the corticonResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorticonResponse(String value) {
        this.corticonResponse = value;
    }

    /**
     * Gets the value of the currentDispatchId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCurrentDispatchId() {
        return currentDispatchId;
    }

    /**
     * Sets the value of the currentDispatchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCurrentDispatchId(Object value) {
        this.currentDispatchId = value;
    }

    /**
     * Gets the value of the currentStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCurrentStatusCode() {
        return currentStatusCode;
    }

    /**
     * Sets the value of the currentStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCurrentStatusCode(Object value) {
        this.currentStatusCode = value;
    }

    /**
     * Gets the value of the currentServiceClass property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCurrentServiceClass() {
        return currentServiceClass;
    }

    /**
     * Sets the value of the currentServiceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCurrentServiceClass(Object value) {
        this.currentServiceClass = value;
    }

    /**
     * Gets the value of the previousDispatchId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPreviousDispatchId() {
        return previousDispatchId;
    }

    /**
     * Sets the value of the previousDispatchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPreviousDispatchId(Object value) {
        this.previousDispatchId = value;
    }

    /**
     * Gets the value of the previousStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPreviousStatusCode() {
        return previousStatusCode;
    }

    /**
     * Sets the value of the previousStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPreviousStatusCode(Object value) {
        this.previousStatusCode = value;
    }

    /**
     * Gets the value of the previousServiceClass property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPreviousServiceClass() {
        return previousServiceClass;
    }

    /**
     * Sets the value of the previousServiceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPreviousServiceClass(Object value) {
        this.previousServiceClass = value;
    }

}
