DROP TABLE SOAINFR.LOYALTY_STATUS_CODES ;
COMMIT ;

CREATE TABLE SHOPPING.LOYALTY_STATUS_CODES ( 
  "LOYALTY_STATUS" INTEGER NOT NULL , 
  "STATUS" VARCHAR(20) 
, CONSTRAINT "LOYALTY_STATUS_CODES_PK" PRIMARY KEY ( "LOYALTY_STATUS" ) );
COMMIT;
